name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod
        working-directory: docs 
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
        working-directory: docs 

      - name: Check baseurl
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "BASE_URL=$baseurl" >> $GITHUB_ENV
          fi
        working-directory: docs        

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b -d "_site$BASE_URL"
        working-directory: docs

      - name: Test Site
        run: |
          bash tools/test.sh
        working-directory: docs

      - name: Deploy
        run: |
          if [[ -n $BASE_URL ]]; then
            mv _site$BASE_URL _site-rename
            rm -rf _site
            mv _site-rename _site
          fi

          bash tools/deploy.sh
        working-directory: docs
